name: Deploy Supabase

on:
  workflow_call:
    inputs:
      project-id:
        required: true
        type: string
    secrets:
      token:
        required: true
      db-password:
        required: true

jobs:
  deploy:
    name: Setup & deploy Supabase
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.token }}
      SUPABASE_DB_PASSWORD: ${{ secrets.db-password }}
      PROJECT_ID: ${{ inputs.project-id }}

    steps:
      - name: Log deployment info
        run: |
          echo Deploying Supabase from ${{ github.ref_name }} to project id $PROJECT_ID
      
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to environment    
        run: supabase link --project-ref $PROJECT_ID
        
      - name: Deploy functions
        run: supabase functions deploy --import-map import-map.json 
        
      - name: Push db changes    
        run: supabase db push
          
